In [1]:
%load_ext autoreload
%autoreload 2

In [2]:
import torch
import numpy as np

from src.utils import (
    get_args,
    set_seed,
    get_datesets_and_loaders,
    get_trained_VAE,
    get_trained_VAE_with_domain_classifier,
    get_trained_classifier,
    get_trained_classifier_Base,
    test_model,
    prepare_report,
    run_all_senario
)

/home/asad/workspace/DomainProject/changeDomain/notebooks/effective-gzsda/gzsda/src/utils.py:3: UserWarning: A NumPy version >=1.22.4 and <2.3.0 is required for this version of SciPy (detected version 2.3.1)
  import scipy

In [3]:

DOMAIN_SET = ['angry', 'childlike', 'depressed', 'neutral', 'old', 'proud', 'strutting']
DATA_DIR = './data/ActionStyleDataset/'
DATASET_DETAILS = {
    'prefix': 'ActionStyle-',
    'suffix': '-clip.mat',
    'resnet_feature': 'clip_features',
    'split_file_name': 'instanceSplit_actionStyle_unseen2.mat',
}
NUM_LABELS = 5

In [4]:
import sys

sys.argv.extend([
    "--encoder_layer_sizes", "512", "512",
    "--decoder_layer_sizes", "512", "512",
])

In [5]:
result = {}

## Base

In [6]:
def main_base(args):
    set_seed(args)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    datasets, data_loaders = get_datesets_and_loaders(
        args=args,
        DOMAIN_SET=DOMAIN_SET,
        DATA_DIR=DATA_DIR,
        DATASET_DETAILS=DATASET_DETAILS)

    classifier = get_trained_classifier_Base(
        data_loaders=data_loaders,
        NUM_LABELS=NUM_LABELS,
        device=device,
        input_dim=512)

    return test_model(classifier, datasets['test'], data_loaders['test'], device)

In [7]:
result["Base"] = run_all_senario(main_base, DOMAIN_SET, input_dim=512, num_trial=6)

angry -> childlike
per-class acc:0.7120, seen acc:0.9375, unseen acc:0.4865, H:0.6406
per-class acc:0.5122, seen acc:0.9375, unseen acc:0.0870, H:0.1592
per-class acc:0.5435, seen acc:1.0000, unseen acc:0.0870, H:0.1600
per-class acc:0.7432, seen acc:0.8125, unseen acc:0.6739, H:0.7367
per-class acc:0.7016, seen acc:0.9167, unseen acc:0.4865, H:0.6356
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     93.40 ± 2.82
Unseen:   30.35 ± 11.40
H-mean:   38.87 ± 12.93
angry -> depressed
per-class acc:0.5103, seen acc:0.9231, unseen acc:0.0976, H:0.1765
per-class acc:0.5598, seen acc:1.0000, unseen acc:0.1196, H:0.2136
per-class acc:0.6413, seen acc:1.0000, unseen acc:0.2826, H:0.4407
per-class acc:0.5997, seen acc:0.9091, unseen acc:0.2903, H:0.4401
per-class acc:0.4855, seen acc:0.8125, unseen acc:0.1585, H:0.2653
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     94.08 ± 3.07
Unseen:   15.81 ± 4.59
H-mean:   25.60 ± 6.87
angry -> neutral
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6667, seen acc:1.0000, unseen acc:0.3333, H:0.5000
per-class acc:0.7037, seen acc:1.0000, unseen acc:0.4074, H:0.5789
per-class acc:0.9537, seen acc:1.0000, unseen acc:0.9074, H:0.9515
per-class acc:0.6667, seen acc:0.8333, unseen acc:0.5000, H:0.6250
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     97.22 ± 2.78
Unseen:   44.14 ± 12.00
H-mean:   55.37 ± 12.73
angry -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4297, seen acc:0.8125, unseen acc:0.0469, H:0.0886
per-class acc:0.6562, seen acc:1.0000, unseen acc:0.3125, H:0.4762
per-class acc:0.4401, seen acc:0.8333, unseen acc:0.0469, H:0.0888
per-class acc:0.5102, seen acc:0.9000, unseen acc:0.1204, H:0.2124
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     92.43 ± 3.58
Unseen:   8.78 ± 4.84
H-mean:   14.43 ± 7.36
angry -> proud
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6447, seen acc:1.0000, unseen acc:0.2895, H:0.4490
per-class acc:0.6908, seen acc:1.0000, unseen acc:0.3816, H:0.5524
per-class acc:0.9211, seen acc:1.0000, unseen acc:0.8421, H:0.9143
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     100.00 ± 0.00
Unseen:   41.89 ± 11.34
H-mean:   54.15 ± 12.55
angry -> strutting
per-class acc:0.7059, seen acc:1.0000, unseen acc:0.4118, H:0.5833
per-class acc:0.6596, seen acc:1.0000, unseen acc:0.3191, H:0.4839
per-class acc:0.7021, seen acc:1.0000, unseen acc:0.4043, H:0.5758
per-class acc:0.9108, seen acc:1.0000, unseen acc:0.8217, H:0.9021
per-class acc:0.6779, seen acc:0.9000, unseen acc:0.4559, H:0.6052
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     98.33 ± 1.67
Unseen:   40.21 ± 10.76
H-mean:   52.50 ± 12.00
childlike -> angry
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5619, seen acc:1.0000, unseen acc:0.1238, H:0.2203
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     97.92 ± 2.08
Unseen:   27.06 ± 10.42
H-mean:   36.50 ± 13.45
childlike -> depressed
per-class acc:0.5225, seen acc:0.9231, unseen acc:0.1220, H:0.2154
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5061, seen acc:1.0000, unseen acc:0.0122, H:0.0241
per-class acc:0.4289, seen acc:0.8333, unseen acc:0.0244, H:0.0474
per-class acc:0.4821, seen acc:0.9643, unseen acc:0.0000, H:0.0000
Seen:     95.34 ± 2.71
Unseen:   2.64 ± 1.95
H-mean:   4.78 ± 3.44
childlike -> neutral
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.6633, seen acc:1.0000, unseen acc:0.3265, H:0.4923
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7609, seen acc:1.0000, unseen acc:0.5217, H:0.6857
per-class acc:0.4773, seen acc:0.9545, unseen acc:0.0000, H:0.0000
Seen:     97.16 ± 2.07
Unseen:   30.80 ± 10.16
H-mean:   41.35 ± 13.37
childlike -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4532, seen acc:0.8846, unseen acc:0.0217, H:0.0424
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     95.30 ± 3.05
Unseen:   0.36 ± 0.36
H-mean:   0.71 ± 0.71
childlike -> proud
per-class acc:0.7064, seen acc:0.9583, unseen acc:0.4545, H:0.6166
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.6950, seen acc:1.0000, unseen acc:0.3900, H:0.5611
per-class acc:0.7273, seen acc:1.0000, unseen acc:0.4545, H:0.6250
per-class acc:0.7292, seen acc:0.9583, unseen acc:0.5000, H:0.6571
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     98.61 ± 0.88
Unseen:   29.98 ± 9.59
H-mean:   41.00 ± 13.03
childlike -> strutting
per-class acc:0.7206, seen acc:1.0000, unseen acc:0.4412, H:0.6122
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7353, seen acc:1.0000, unseen acc:0.4706, H:0.6400
per-class acc:0.6572, seen acc:0.8438, unseen acc:0.4706, H:0.6042
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     97.40 ± 2.60
Unseen:   23.04 ± 10.31
H-mean:   30.94 ± 13.85
depressed -> angry
per-class acc:0.6562, seen acc:0.8125, unseen acc:0.5000, H:0.6190
per-class acc:0.6471, seen acc:1.0000, unseen acc:0.2941, H:0.4545
per-class acc:0.6797, seen acc:0.8889, unseen acc:0.4706, H:0.6154
per-class acc:0.8971, seen acc:1.0000, unseen acc:0.7941, H:0.8852
per-class acc:0.5750, seen acc:0.6500, unseen acc:0.5000, H:0.5652
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     89.19 ± 5.77
Unseen:   42.65 ± 10.76
H-mean:   52.32 ± 11.96
depressed -> childlike
per-class acc:0.4685, seen acc:0.6667, unseen acc:0.2703, H:0.3846
per-class acc:0.4280, seen acc:0.8125, unseen acc:0.0435, H:0.0825
per-class acc:0.5127, seen acc:0.9167, unseen acc:0.1087, H:0.1943
per-class acc:0.8366, seen acc:0.8036, unseen acc:0.8696, H:0.8353
per-class acc:0.5034, seen acc:0.7500, unseen acc:0.2568, H:0.3826
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     82.49 ± 4.84
Unseen:   25.81 ± 13.03
H-mean:   31.32 ± 12.22
depressed -> neutral
per-class acc:0.6818, seen acc:0.8636, unseen acc:0.5000, H:0.6333
per-class acc:0.6111, seen acc:1.0000, unseen acc:0.2222, H:0.3636
per-class acc:0.6597, seen acc:0.8750, unseen acc:0.4444, H:0.5895
per-class acc:0.8981, seen acc:1.0000, unseen acc:0.7963, H:0.8866
per-class acc:0.5833, seen acc:0.6667, unseen acc:0.5000, H:0.5714
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     90.09 ± 5.37
Unseen:   41.05 ± 11.11
H-mean:   50.74 ± 12.23
depressed -> old
per-class acc:0.6522, seen acc:1.0000, unseen acc:0.3043, H:0.4667
per-class acc:0.6406, seen acc:0.9375, unseen acc:0.3438, H:0.5030
per-class acc:0.6719, seen acc:1.0000, unseen acc:0.3438, H:0.5116
per-class acc:0.9018, seen acc:1.0000, unseen acc:0.8037, H:0.8911
per-class acc:0.6739, seen acc:1.0000, unseen acc:0.3478, H:0.5161
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     98.96 ± 1.04
Unseen:   35.72 ± 10.49
H-mean:   48.14 ± 11.58
depressed -> proud
per-class acc:0.5417, seen acc:0.5833, unseen acc:0.5000, H:0.5385
per-class acc:0.6184, seen acc:1.0000, unseen acc:0.2368, H:0.3830
per-class acc:0.4211, seen acc:0.5000, unseen acc:0.3421, H:0.4063
per-class acc:0.9095, seen acc:0.9375, unseen acc:0.8816, H:0.9087
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     83.68 ± 9.45
Unseen:   41.01 ± 12.13
H-mean:   48.38 ± 12.48
depressed -> strutting
per-class acc:0.4779, seen acc:0.5000, unseen acc:0.4559, H:0.4769
per-class acc:0.5532, seen acc:1.0000, unseen acc:0.1064, H:0.1923
per-class acc:0.3723, seen acc:0.5000, unseen acc:0.2447, H:0.3286
per-class acc:0.7041, seen acc:0.6250, unseen acc:0.7832, H:0.6952
per-class acc:0.6279, seen acc:0.8000, unseen acc:0.4559, H:0.5808
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     73.75 ± 9.44
Unseen:   34.10 ± 11.58
H-mean:   37.90 ± 10.51
neutral -> angry
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.4643, seen acc:0.9286, unseen acc:0.0000, H:0.0000
per-class acc:0.5515, seen acc:1.0000, unseen acc:0.1029, H:0.1867
per-class acc:0.7868, seen acc:1.0000, unseen acc:0.5735, H:0.7290
per-class acc:0.7250, seen acc:0.9500, unseen acc:0.5000, H:0.6552
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     97.98 ± 1.31
Unseen:   27.94 ± 11.12
H-mean:   37.29 ± 14.21
neutral -> childlike
per-class acc:0.7120, seen acc:0.9375, unseen acc:0.4865, H:0.6406
per-class acc:0.3125, seen acc:0.6250, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.6930, seen acc:0.8125, unseen acc:0.5734, H:0.6724
per-class acc:0.6708, seen acc:0.8333, unseen acc:0.5082, H:0.6314
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     86.81 ± 5.86
Unseen:   26.14 ± 11.75
H-mean:   32.41 ± 14.50
neutral -> depressed
per-class acc:0.6811, seen acc:0.9231, unseen acc:0.4390, H:0.5950
per-class acc:0.3750, seen acc:0.7500, unseen acc:0.0000, H:0.0000
per-class acc:0.4286, seen acc:0.8571, unseen acc:0.0000, H:0.0000
per-class acc:0.6741, seen acc:0.9091, unseen acc:0.4390, H:0.5921
per-class acc:0.7864, seen acc:0.8750, unseen acc:0.6978, H:0.7764
per-class acc:0.4821, seen acc:0.9643, unseen acc:0.0000, H:0.0000
Seen:     87.98 ± 3.01
Unseen:   26.26 ± 12.36
H-mean:   32.73 ± 14.89
neutral -> old
per-class acc:0.6522, seen acc:1.0000, unseen acc:0.3043, H:0.4667
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5580, seen acc:0.8333, unseen acc:0.2826, H:0.4221
per-class acc:0.9090, seen acc:0.9000, unseen acc:0.9181, H:0.9089
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     84.44 ± 7.54
Unseen:   25.08 ± 14.58
H-mean:   29.96 ± 15.09
neutral -> proud
per-class acc:0.7292, seen acc:0.9583, unseen acc:0.5000, H:0.6571
per-class acc:0.4441, seen acc:0.8750, unseen acc:0.0132, H:0.0259
per-class acc:0.5263, seen acc:1.0000, unseen acc:0.0526, H:0.1000
per-class acc:0.8947, seen acc:1.0000, unseen acc:0.7895, H:0.8824
per-class acc:0.7625, seen acc:1.0000, unseen acc:0.5250, H:0.6885
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     97.22 ± 2.06
Unseen:   31.34 ± 13.69
H-mean:   39.23 ± 16.04
neutral -> strutting
per-class acc:0.7426, seen acc:1.0000, unseen acc:0.4853, H:0.6535
per-class acc:0.4583, seen acc:0.9167, unseen acc:0.0000, H:0.0000
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.8969, seen acc:1.0000, unseen acc:0.7938, H:0.8851
per-class acc:0.6926, seen acc:0.9000, unseen acc:0.4853, H:0.6306
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     88.61 ± 7.94
Unseen:   29.41 ± 13.93
H-mean:   36.15 ± 16.57
old -> angry
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5662, seen acc:1.0000, unseen acc:0.1324, H:0.2338
per-class acc:0.6871, seen acc:0.8889, unseen acc:0.4853, H:0.6278
per-class acc:0.3588, seen acc:0.6000, unseen acc:0.1176, H:0.1967
per-class acc:0.4500, seen acc:0.9000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     81.48 ± 8.69
Unseen:   12.25 ± 7.68
H-mean:   17.64 ± 10.01
old -> childlike
per-class acc:0.2593, seen acc:0.5000, unseen acc:0.0185, H:0.0357
per-class acc:0.6087, seen acc:1.0000, unseen acc:0.2174, H:0.3571
per-class acc:0.5998, seen acc:0.8333, unseen acc:0.3663, H:0.5089
per-class acc:0.4053, seen acc:0.5714, unseen acc:0.2391, H:0.3372
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     81.75 ± 9.34
Unseen:   14.02 ± 6.35
H-mean:   20.65 ± 9.05
old -> depressed
per-class acc:0.3929, seen acc:0.7857, unseen acc:0.0000, H:0.0000
per-class acc:0.5588, seen acc:0.9545, unseen acc:0.1630, H:0.2785
per-class acc:0.5652, seen acc:0.7143, unseen acc:0.4161, H:0.5259
per-class acc:0.4873, seen acc:0.8333, unseen acc:0.1413, H:0.2416
per-class acc:0.4833, seen acc:0.9667, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     86.93 ± 4.38
Unseen:   12.01 ± 6.66
H-mean:   17.43 ± 8.76
old -> neutral
per-class acc:0.4318, seen acc:0.8636, unseen acc:0.0000, H:0.0000
per-class acc:0.5278, seen acc:1.0000, unseen acc:0.0556, H:0.1053
per-class acc:0.6100, seen acc:0.8125, unseen acc:0.4074, H:0.5427
per-class acc:0.4653, seen acc:0.8750, unseen acc:0.0556, H:0.1045
per-class acc:0.3889, seen acc:0.7778, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     88.82 ± 3.82
Unseen:   8.64 ± 6.52
H-mean:   12.54 ± 8.61
old -> proud
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5987, seen acc:1.0000, unseen acc:0.1974, H:0.3297
per-class acc:0.4897, seen acc:0.5714, unseen acc:0.4079, H:0.4760
per-class acc:0.4934, seen acc:0.7500, unseen acc:0.2368, H:0.3600
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     80.36 ± 9.39
Unseen:   14.04 ± 6.91
H-mean:   19.43 ± 8.91
old -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4149, seen acc:0.5000, unseen acc:0.3298, H:0.3974
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4500, seen acc:0.9000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     73.33 ± 10.54
Unseen:   5.50 ± 5.50
H-mean:   6.62 ± 6.62
proud -> angry
per-class acc:0.4688, seen acc:0.9375, unseen acc:0.0000, H:0.0000
per-class acc:0.7262, seen acc:0.7857, unseen acc:0.6667, H:0.7213
per-class acc:0.7426, seen acc:1.0000, unseen acc:0.4853, H:0.6535
per-class acc:0.8426, seen acc:0.7000, unseen acc:0.9853, H:0.8185
per-class acc:0.2571, seen acc:0.5000, unseen acc:0.0143, H:0.0278
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     82.05 ± 8.09
Unseen:   35.86 ± 17.12
H-mean:   37.02 ± 16.29
proud -> childlike
per-class acc:0.3854, seen acc:0.7708, unseen acc:0.0000, H:0.0000
per-class acc:0.5421, seen acc:0.5625, unseen acc:0.5217, H:0.5414
per-class acc:0.7283, seen acc:1.0000, unseen acc:0.4565, H:0.6269
per-class acc:0.7528, seen acc:0.5625, unseen acc:0.9430, H:0.7047
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4792, seen acc:0.9583, unseen acc:0.0000, H:0.0000
Seen:     72.57 ± 8.86
Unseen:   32.02 ± 15.86
H-mean:   31.21 ± 14.12
proud -> depressed
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5367, seen acc:0.6000, unseen acc:0.4734, H:0.5293
per-class acc:0.6793, seen acc:1.0000, unseen acc:0.3587, H:0.5280
per-class acc:0.5593, seen acc:0.7273, unseen acc:0.3913, H:0.5088
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     79.81 ± 8.97
Unseen:   20.39 ± 9.25
H-mean:   26.10 ± 11.68
proud -> neutral
per-class acc:0.4773, seen acc:0.9545, unseen acc:0.0000, H:0.0000
per-class acc:0.5823, seen acc:0.6429, unseen acc:0.5217, H:0.5760
per-class acc:0.7315, seen acc:1.0000, unseen acc:0.4630, H:0.6329
per-class acc:0.7815, seen acc:0.6000, unseen acc:0.9630, H:0.7393
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     78.29 ± 9.25
Unseen:   32.46 ± 16.14
H-mean:   32.47 ± 14.68
proud -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4688, seen acc:0.5000, unseen acc:0.4375, H:0.4667
per-class acc:0.7109, seen acc:1.0000, unseen acc:0.4219, H:0.5934
per-class acc:0.5321, seen acc:0.6111, unseen acc:0.4531, H:0.5204
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4688, seen acc:0.9375, unseen acc:0.0000, H:0.0000
Seen:     75.81 ± 10.07
Unseen:   21.88 ± 9.79
H-mean:   26.34 ± 11.89
proud -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5417, seen acc:0.5833, unseen acc:0.5000, H:0.5385
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5500, seen acc:0.6000, unseen acc:0.5000, H:0.5455
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     69.72 ± 9.72
Unseen:   25.00 ± 11.18
H-mean:   29.18 ± 13.18
strutting -> angry
per-class acc:0.4714, seen acc:0.5000, unseen acc:0.4429, H:0.4697
per-class acc:0.7279, seen acc:1.0000, unseen acc:0.4559, H:0.6263
per-class acc:0.4853, seen acc:0.5000, unseen acc:0.4706, H:0.4848
per-class acc:0.7279, seen acc:0.5000, unseen acc:0.9559, H:0.6566
per-class acc:0.4571, seen acc:0.5000, unseen acc:0.4143, H:0.4531
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     66.67 ± 10.54
Unseen:   45.66 ± 12.38
H-mean:   44.84 ± 9.62
strutting -> childlike
per-class acc:0.4122, seen acc:0.5000, unseen acc:0.3243, H:0.3934
per-class acc:0.6848, seen acc:1.0000, unseen acc:0.3696, H:0.5397
per-class acc:0.4348, seen acc:0.5000, unseen acc:0.3696, H:0.4250
per-class acc:0.7174, seen acc:0.5000, unseen acc:0.9348, H:0.6515
per-class acc:0.4189, seen acc:0.5000, unseen acc:0.3378, H:0.4032
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     66.67 ± 10.54
Unseen:   38.93 ± 12.34
H-mean:   40.21 ± 9.01
strutting -> depressed
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.6359, seen acc:1.0000, unseen acc:0.2717, H:0.4274
per-class acc:0.4239, seen acc:0.5000, unseen acc:0.3478, H:0.4103
per-class acc:0.5962, seen acc:0.4545, unseen acc:0.7378, H:0.5625
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     65.27 ± 10.41
Unseen:   22.62 ± 12.00
H-mean:   23.34 ± 10.66
strutting -> neutral
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7130, seen acc:1.0000, unseen acc:0.4259, H:0.5974
per-class acc:0.4722, seen acc:0.5000, unseen acc:0.4444, H:0.4706
per-class acc:0.7315, seen acc:0.5000, unseen acc:0.9630, H:0.6582
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     66.67 ± 10.54
Unseen:   47.22 ± 12.49
H-mean:   45.44 ± 9.54
strutting -> old
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5234, seen acc:0.9375, unseen acc:0.1094, H:0.1959
per-class acc:0.4141, seen acc:0.5000, unseen acc:0.3281, H:0.3962
per-class acc:0.3217, seen acc:0.5000, unseen acc:0.1433, H:0.2228
per-class acc:0.3500, seen acc:0.7000, unseen acc:0.0000, H:0.0000

# GZSDA

In [8]:
def main_gzsda(args):
    set_seed(args)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    datasets, data_loaders = get_datesets_and_loaders(
        args=args,
        DOMAIN_SET=DOMAIN_SET,
        DATA_DIR=DATA_DIR,
        DATASET_DETAILS=DATASET_DETAILS)

    vae = get_trained_VAE(
        data_loaders=data_loaders,
        args=args,
        device=device)

    classifier = get_trained_classifier(
        data_loaders=data_loaders,
        vae=vae,
        NUM_LABELS=NUM_LABELS,
        device=device,
        input_dim=512)

    return test_model(classifier, datasets['test'], data_loaders['test'], device)

In [9]:
result["GZSDA"] = run_all_senario(main_gzsda, DOMAIN_SET, input_dim=512, num_trial=6)

angry -> childlike
per-class acc:0.7120, seen acc:0.9375, unseen acc:0.4865, H:0.6406
per-class acc:0.4688, seen acc:0.9375, unseen acc:0.0000, H:0.0000
per-class acc:0.5109, seen acc:1.0000, unseen acc:0.0217, H:0.0426
per-class acc:0.7106, seen acc:0.8125, unseen acc:0.6087, H:0.6960
per-class acc:0.6182, seen acc:0.7500, unseen acc:0.4865, H:0.5902
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     90.62 ± 4.19
Unseen:   26.72 ± 11.77
H-mean:   32.82 ± 14.12
angry -> depressed
per-class acc:0.4737, seen acc:0.9231, unseen acc:0.0244, H:0.0475
per-class acc:0.5272, seen acc:1.0000, unseen acc:0.0543, H:0.1031
per-class acc:0.5761, seen acc:1.0000, unseen acc:0.1522, H:0.2642
per-class acc:0.5610, seen acc:0.9091, unseen acc:0.2129, H:0.3450
per-class acc:0.3742, seen acc:0.6875, unseen acc:0.0610, H:0.1120
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     91.99 ± 4.95
Unseen:   8.41 ± 3.33
H-mean:   14.53 ± 5.40
angry -> neutral
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6111, seen acc:1.0000, unseen acc:0.2222, H:0.3636
per-class acc:0.6944, seen acc:1.0000, unseen acc:0.3889, H:0.5600
per-class acc:0.8889, seen acc:1.0000, unseen acc:0.7778, H:0.8750
per-class acc:0.6389, seen acc:0.7778, unseen acc:0.5000, H:0.6087
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     96.30 ± 3.70
Unseen:   39.81 ± 10.87
H-mean:   51.23 ± 12.27
angry -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4141, seen acc:0.8125, unseen acc:0.0156, H:0.0307
per-class acc:0.5859, seen acc:1.0000, unseen acc:0.1719, H:0.2933
per-class acc:0.4245, seen acc:0.8333, unseen acc:0.0156, H:0.0307
per-class acc:0.4500, seen acc:0.9000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     92.43 ± 3.58
Unseen:   3.39 ± 2.78
H-mean:   5.91 ± 4.72
angry -> proud
per-class acc:0.7273, seen acc:1.0000, unseen acc:0.4545, H:0.6250
per-class acc:0.6118, seen acc:1.0000, unseen acc:0.2237, H:0.3656
per-class acc:0.6513, seen acc:1.0000, unseen acc:0.3026, H:0.4646
per-class acc:0.8834, seen acc:1.0000, unseen acc:0.7667, H:0.8680
per-class acc:0.7273, seen acc:1.0000, unseen acc:0.4545, H:0.6250
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     100.00 ± 0.00
Unseen:   36.70 ± 10.56
H-mean:   49.14 ± 12.05
angry -> strutting
per-class acc:0.7132, seen acc:1.0000, unseen acc:0.4265, H:0.5979
per-class acc:0.6117, seen acc:1.0000, unseen acc:0.2234, H:0.3652
per-class acc:0.6436, seen acc:1.0000, unseen acc:0.2872, H:0.4463
per-class acc:0.8969, seen acc:1.0000, unseen acc:0.7938, H:0.8851
per-class acc:0.6059, seen acc:0.8000, unseen acc:0.4118, H:0.5437
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     96.67 ± 3.33
Unseen:   35.71 ± 10.78
H-mean:   47.30 ± 11.92
childlike -> angry
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     97.92 ± 2.08
Unseen:   25.00 ± 11.18
H-mean:   32.83 ± 14.69
childlike -> depressed
per-class acc:0.5286, seen acc:0.9231, unseen acc:0.1341, H:0.2343
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4643, seen acc:0.9286, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4228, seen acc:0.8333, unseen acc:0.0122, H:0.0240
per-class acc:0.4821, seen acc:0.9643, unseen acc:0.0000, H:0.0000
Seen:     94.15 ± 2.55
Unseen:   2.44 ± 2.20
H-mean:   4.30 ± 3.84
childlike -> neutral
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.4773, seen acc:0.9545, unseen acc:0.0000, H:0.0000
Seen:     97.16 ± 2.07
Unseen:   25.00 ± 11.18
H-mean:   32.83 ± 14.69
childlike -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4423, seen acc:0.8846, unseen acc:0.0000, H:0.0000
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     95.30 ± 3.05
Unseen:   0.00 ± 0.00
H-mean:   0.00 ± 0.00
childlike -> proud
per-class acc:0.7064, seen acc:0.9583, unseen acc:0.4545, H:0.6166
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7159, seen acc:1.0000, unseen acc:0.4318, H:0.6032
per-class acc:0.7178, seen acc:0.9583, unseen acc:0.4773, H:0.6372
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     98.61 ± 0.88
Unseen:   22.73 ± 10.18
H-mean:   30.95 ± 13.85
childlike -> strutting
per-class acc:0.7426, seen acc:1.0000, unseen acc:0.4853, H:0.6535
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.3750, seen acc:0.7500, unseen acc:0.0000, H:0.0000
per-class acc:0.7206, seen acc:1.0000, unseen acc:0.4412, H:0.6122
per-class acc:0.6434, seen acc:0.8750, unseen acc:0.4118, H:0.5600
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     93.75 ± 4.27
Unseen:   22.30 ± 10.02
H-mean:   30.43 ± 13.66
depressed -> angry
per-class acc:0.4571, seen acc:0.5000, unseen acc:0.4143, H:0.4531
per-class acc:0.5662, seen acc:1.0000, unseen acc:0.1324, H:0.2338
per-class acc:0.4412, seen acc:0.5000, unseen acc:0.3824, H:0.4333
per-class acc:0.7235, seen acc:0.8000, unseen acc:0.6471, H:0.7154
per-class acc:0.5393, seen acc:0.6500, unseen acc:0.4286, H:0.5166
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     74.17 ± 9.35
Unseen:   33.41 ± 9.45
H-mean:   39.20 ± 10.07
depressed -> childlike
per-class acc:0.2973, seen acc:0.5000, unseen acc:0.0946, H:0.1591
per-class acc:0.4062, seen acc:0.8125, unseen acc:0.0000, H:0.0000
per-class acc:0.3750, seen acc:0.7500, unseen acc:0.0000, H:0.0000
per-class acc:0.6435, seen acc:0.5179, unseen acc:0.7691, H:0.6190
per-class acc:0.4291, seen acc:0.7500, unseen acc:0.1081, H:0.1890
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     72.17 ± 7.70
Unseen:   16.20 ± 12.31
H-mean:   16.12 ± 9.80
depressed -> neutral
per-class acc:0.6591, seen acc:0.8182, unseen acc:0.5000, H:0.6207
per-class acc:0.5741, seen acc:1.0000, unseen acc:0.1481, H:0.2581
per-class acc:0.4792, seen acc:0.6250, unseen acc:0.3333, H:0.4348
per-class acc:0.8611, seen acc:1.0000, unseen acc:0.7222, H:0.8387
per-class acc:0.6111, seen acc:0.7222, unseen acc:0.5000, H:0.5909
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     86.09 ± 6.70
Unseen:   36.73 ± 10.73
H-mean:   45.72 ± 12.10
depressed -> old
per-class acc:0.5152, seen acc:0.9000, unseen acc:0.1304, H:0.2278
per-class acc:0.6094, seen acc:1.0000, unseen acc:0.2188, H:0.3590
per-class acc:0.3906, seen acc:0.5000, unseen acc:0.2812, H:0.3600
per-class acc:0.7446, seen acc:1.0000, unseen acc:0.4891, H:0.6569
per-class acc:0.5761, seen acc:1.0000, unseen acc:0.1522, H:0.2642
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     90.00 ± 8.16
Unseen:   21.20 ± 6.75
H-mean:   31.13 ± 8.76
depressed -> proud
per-class acc:0.3977, seen acc:0.5000, unseen acc:0.2955, H:0.3714
per-class acc:0.6053, seen acc:1.0000, unseen acc:0.2105, H:0.3478
per-class acc:0.3618, seen acc:0.5000, unseen acc:0.2237, H:0.3091
per-class acc:0.8388, seen acc:0.8750, unseen acc:0.8026, H:0.8373
per-class acc:0.6136, seen acc:1.0000, unseen acc:0.2273, H:0.3704
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     81.25 ± 10.08
Unseen:   29.33 ± 10.98
H-mean:   37.27 ± 10.95
depressed -> strutting
per-class acc:0.3897, seen acc:0.5000, unseen acc:0.2794, H:0.3585
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.3032, seen acc:0.5000, unseen acc:0.1064, H:0.1754
per-class acc:0.5033, seen acc:0.5000, unseen acc:0.5066, H:0.5033
per-class acc:0.5471, seen acc:0.8000, unseen acc:0.2941, H:0.4301
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     71.67 ± 10.14
Unseen:   19.77 ± 8.12
H-mean:   24.46 ± 8.92
neutral -> angry
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.4643, seen acc:0.9286, unseen acc:0.0000, H:0.0000
per-class acc:0.4722, seen acc:0.9444, unseen acc:0.0000, H:0.0000
per-class acc:0.7794, seen acc:1.0000, unseen acc:0.5588, H:0.7170
per-class acc:0.7250, seen acc:0.9500, unseen acc:0.5000, H:0.6552
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     97.05 ± 1.35
Unseen:   25.98 ± 11.65
H-mean:   33.98 ± 15.22
neutral -> childlike
per-class acc:0.7188, seen acc:0.9375, unseen acc:0.5000, H:0.6522
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4583, seen acc:0.9167, unseen acc:0.0000, H:0.0000
per-class acc:0.6671, seen acc:0.8125, unseen acc:0.5217, H:0.6354
per-class acc:0.6667, seen acc:0.8333, unseen acc:0.5000, H:0.6250
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     80.56 ± 6.45
Unseen:   25.36 ± 11.35
H-mean:   31.88 ± 14.26
neutral -> depressed
per-class acc:0.6811, seen acc:0.9231, unseen acc:0.4390, H:0.5950
per-class acc:0.3000, seen acc:0.6000, unseen acc:0.0000, H:0.0000
per-class acc:0.3929, seen acc:0.7857, unseen acc:0.0000, H:0.0000
per-class acc:0.6513, seen acc:0.8636, unseen acc:0.4390, H:0.5821
per-class acc:0.6128, seen acc:0.7500, unseen acc:0.4756, H:0.5821
per-class acc:0.4643, seen acc:0.9286, unseen acc:0.0000, H:0.0000
Seen:     80.85 ± 5.10
Unseen:   22.56 ± 10.10
H-mean:   29.32 ± 13.11
neutral -> old
per-class acc:0.6630, seen acc:1.0000, unseen acc:0.3261, H:0.4918
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5797, seen acc:0.8333, unseen acc:0.3261, H:0.4688
per-class acc:0.6667, seen acc:0.8000, unseen acc:0.5334, H:0.6401
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     82.78 ± 7.47
Unseen:   19.76 ± 9.36
H-mean:   26.68 ± 12.17
neutral -> proud
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.4375, seen acc:0.8750, unseen acc:0.0000, H:0.0000
per-class acc:0.4286, seen acc:0.8571, unseen acc:0.0000, H:0.0000
per-class acc:0.8947, seen acc:1.0000, unseen acc:0.7895, H:0.8824
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     95.54 ± 2.83
Unseen:   29.82 ± 14.02
H-mean:   36.93 ± 16.82
neutral -> strutting
per-class acc:0.7426, seen acc:1.0000, unseen acc:0.4853, H:0.6535
per-class acc:0.2917, seen acc:0.5833, unseen acc:0.0000, H:0.0000
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.8863, seen acc:1.0000, unseen acc:0.7725, H:0.8717
per-class acc:0.6426, seen acc:0.8000, unseen acc:0.4853, H:0.6041
per-class acc:0.4792, seen acc:0.9583, unseen acc:0.0000, H:0.0000
Seen:     80.69 ± 8.98
Unseen:   29.05 ± 13.68
H-mean:   35.49 ± 16.29
old -> angry
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5294, seen acc:1.0000, unseen acc:0.0588, H:0.1111
per-class acc:0.5891, seen acc:0.7222, unseen acc:0.4559, H:0.5589
per-class acc:0.2794, seen acc:0.5000, unseen acc:0.0588, H:0.1053
per-class acc:0.4250, seen acc:0.8500, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     76.20 ± 9.31
Unseen:   9.56 ± 7.30
H-mean:   12.92 ± 8.86
old -> childlike
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5761, seen acc:1.0000, unseen acc:0.1522, H:0.2642
per-class acc:0.5890, seen acc:0.8333, unseen acc:0.3446, H:0.4876
per-class acc:0.3043, seen acc:0.5000, unseen acc:0.1087, H:0.1786
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     80.56 ± 10.02
Unseen:   10.09 ± 5.56
H-mean:   15.51 ± 8.07
old -> depressed
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4926, seen acc:0.9091, unseen acc:0.0761, H:0.1404
per-class acc:0.4581, seen acc:0.5000, unseen acc:0.4161, H:0.4542
per-class acc:0.2880, seen acc:0.5000, unseen acc:0.0761, H:0.1321
per-class acc:0.4208, seen acc:0.8417, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     70.20 ± 9.17
Unseen:   9.47 ± 6.61
H-mean:   12.11 ± 7.20
old -> neutral
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4630, seen acc:0.5000, unseen acc:0.4259, H:0.4600
per-class acc:0.4062, seen acc:0.8125, unseen acc:0.0000, H:0.0000
per-class acc:0.3889, seen acc:0.7778, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     76.50 ± 9.19
Unseen:   7.10 ± 7.10
H-mean:   7.67 ± 7.67
old -> proud
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5395, seen acc:1.0000, unseen acc:0.0789, H:0.1463
per-class acc:0.4539, seen acc:0.5000, unseen acc:0.4079, H:0.4493
per-class acc:0.3224, seen acc:0.5000, unseen acc:0.1447, H:0.2245
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     75.00 ± 11.18
Unseen:   10.53 ± 6.51
H-mean:   13.67 ± 7.34
old -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4149, seen acc:0.5000, unseen acc:0.3298, H:0.3974
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4000, seen acc:0.8000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     71.67 ± 10.14
Unseen:   5.50 ± 5.50
H-mean:   6.62 ± 6.62
proud -> angry
per-class acc:0.4375, seen acc:0.8750, unseen acc:0.0000, H:0.0000
per-class acc:0.6071, seen acc:0.7143, unseen acc:0.5000, H:0.5882
per-class acc:0.7426, seen acc:1.0000, unseen acc:0.4853, H:0.6535
per-class acc:0.7926, seen acc:0.6000, unseen acc:0.9853, H:0.7458
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     78.15 ± 8.58
Unseen:   32.84 ± 16.42
H-mean:   33.13 ± 14.95
proud -> childlike
per-class acc:0.3333, seen acc:0.6667, unseen acc:0.0000, H:0.0000
per-class acc:0.4891, seen acc:0.5000, unseen acc:0.4783, H:0.4889
per-class acc:0.7283, seen acc:1.0000, unseen acc:0.4565, H:0.6269
per-class acc:0.7215, seen acc:0.5000, unseen acc:0.9430, H:0.6535
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4792, seen acc:0.9583, unseen acc:0.0000, H:0.0000
Seen:     68.75 ± 9.61
Unseen:   31.30 ± 15.69
H-mean:   29.49 ± 13.38
proud -> depressed
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4924, seen acc:0.5500, unseen acc:0.4348, H:0.4857
per-class acc:0.6685, seen acc:1.0000, unseen acc:0.3370, H:0.5041
per-class acc:0.5311, seen acc:0.6818, unseen acc:0.3804, H:0.4884
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     78.22 ± 9.50
Unseen:   19.20 ± 8.68
H-mean:   24.63 ± 11.02
proud -> neutral
per-class acc:0.4773, seen acc:0.9545, unseen acc:0.0000, H:0.0000
per-class acc:0.5265, seen acc:0.5714, unseen acc:0.4815, H:0.5226
per-class acc:0.7315, seen acc:1.0000, unseen acc:0.4630, H:0.6329
per-class acc:0.7763, seen acc:0.6000, unseen acc:0.9525, H:0.7362
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     77.10 ± 9.68
Unseen:   31.62 ± 15.85
H-mean:   31.53 ± 14.37
proud -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4688, seen acc:0.5000, unseen acc:0.4375, H:0.4667
per-class acc:0.7109, seen acc:1.0000, unseen acc:0.4219, H:0.5934
per-class acc:0.5043, seen acc:0.5556, unseen acc:0.4531, H:0.4991
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4688, seen acc:0.9375, unseen acc:0.0000, H:0.0000
Seen:     74.88 ± 10.38
Unseen:   21.88 ± 9.79
H-mean:   25.99 ± 11.75
proud -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4947, seen acc:0.5000, unseen acc:0.4894, H:0.4946
per-class acc:0.7447, seen acc:1.0000, unseen acc:0.4894, H:0.6571
per-class acc:0.4947, seen acc:0.5000, unseen acc:0.4894, H:0.4946
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     66.67 ± 10.54
Unseen:   24.47 ± 10.94
H-mean:   27.44 ± 12.51
strutting -> angry
per-class acc:0.3214, seen acc:0.5000, unseen acc:0.1429, H:0.2222
per-class acc:0.7279, seen acc:1.0000, unseen acc:0.4559, H:0.6263
per-class acc:0.4779, seen acc:0.5000, unseen acc:0.4559, H:0.4769
per-class acc:0.7279, seen acc:0.5000, unseen acc:0.9559, H:0.6566
per-class acc:0.3214, seen acc:0.5000, unseen acc:0.1429, H:0.2222
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     66.67 ± 10.54
Unseen:   35.89 ± 14.11
H-mean:   36.74 ± 10.64
strutting -> childlike
per-class acc:0.3311, seen acc:0.5000, unseen acc:0.1622, H:0.2449
per-class acc:0.5802, seen acc:0.8125, unseen acc:0.3478, H:0.4871
per-class acc:0.4239, seen acc:0.5000, unseen acc:0.3478, H:0.4103
per-class acc:0.7283, seen acc:0.5000, unseen acc:0.9565, H:0.6567
per-class acc:0.3243, seen acc:0.5000, unseen acc:0.1486, H:0.2292
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     63.54 ± 8.90
Unseen:   32.72 ± 13.70
H-mean:   33.80 ± 9.38
strutting -> depressed
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5913, seen acc:0.9000, unseen acc:0.2826, H:0.4301
per-class acc:0.4185, seen acc:0.5000, unseen acc:0.3370, H:0.4026
per-class acc:0.6125, seen acc:0.4545, unseen acc:0.7704, H:0.5718
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     63.60 ± 9.38
Unseen:   23.17 ± 12.45
H-mean:   23.41 ± 10.73
strutting -> neutral
per-class acc:0.4271, seen acc:0.5000, unseen acc:0.3542, H:0.4146
per-class acc:0.7037, seen acc:1.0000, unseen acc:0.4074, H:0.5789
per-class acc:0.4630, seen acc:0.5000, unseen acc:0.4259, H:0.4600
per-class acc:0.7407, seen acc:0.5000, unseen acc:0.9815, H:0.6625
per-class acc:0.4062, seen acc:0.5000, unseen acc:0.3125, H:0.3846
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     66.67 ± 10.54
Unseen:   41.36 ± 13.01
H-mean:   41.68 ± 9.37
strutting -> old
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4844, seen acc:0.8125, unseen acc:0.1562, H:0.2621
per-class acc:0.3984, seen acc:0.5000, unseen acc:0.2969, H:0.3725
per-class acc:0.3421, seen acc:0.5000, unseen acc:0.1841, H:0.2691
per-class acc:0.3500, seen acc:0.7000, unseen acc:0.0000, H:0.0000

## m0

In [10]:
def main_m0(args):
    set_seed(args)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    datasets, data_loaders = get_datesets_and_loaders(
        args=args,
        DOMAIN_SET=DOMAIN_SET,
        DATA_DIR=DATA_DIR,
        DATASET_DETAILS=DATASET_DETAILS)

    vae = get_trained_VAE(
        data_loaders=data_loaders,
        args=args,
        device=device)

    classifier = get_trained_classifier(
        data_loaders=data_loaders,
        vae=vae,
        NUM_LABELS=NUM_LABELS,
        device=device,
        change_policy_epoch=30,
        input_dim=512)

    return test_model(classifier, datasets['test'], data_loaders['test'], device)

In [11]:
result["Our"] = run_all_senario(main_m0, DOMAIN_SET, input_dim=512, num_trial=6)

angry -> childlike
per-class acc:0.6771, seen acc:0.8542, unseen acc:0.5000, H:0.6308
per-class acc:0.6658, seen acc:0.8750, unseen acc:0.4565, H:0.6000
per-class acc:0.7065, seen acc:1.0000, unseen acc:0.4130, H:0.5846
per-class acc:0.8736, seen acc:0.8125, unseen acc:0.9348, H:0.8694
per-class acc:0.5833, seen acc:0.6667, unseen acc:0.5000, H:0.5714
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     86.81 ± 5.12
Unseen:   46.74 ± 12.14
H-mean:   54.27 ± 11.76
angry -> depressed
per-class acc:0.6932, seen acc:0.9231, unseen acc:0.4634, H:0.6171
per-class acc:0.6315, seen acc:0.8500, unseen acc:0.4130, H:0.5559
per-class acc:0.7065, seen acc:1.0000, unseen acc:0.4130, H:0.5846
per-class acc:0.8755, seen acc:0.8636, unseen acc:0.8873, H:0.8753
per-class acc:0.5329, seen acc:0.5625, unseen acc:0.5034, H:0.5313
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     86.65 ± 6.62
Unseen:   44.67 ± 11.54
H-mean:   52.74 ± 11.71
angry -> neutral
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7222, seen acc:1.0000, unseen acc:0.4444, H:0.6154
per-class acc:0.7222, seen acc:1.0000, unseen acc:0.4444, H:0.6154
per-class acc:0.9722, seen acc:1.0000, unseen acc:0.9444, H:0.9714
per-class acc:0.5942, seen acc:0.6667, unseen acc:0.5217, H:0.5854
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     94.44 ± 5.56
Unseen:   47.58 ± 12.26
H-mean:   57.57 ± 12.90
angry -> old
per-class acc:0.6739, seen acc:1.0000, unseen acc:0.3478, H:0.5161
per-class acc:0.6094, seen acc:0.8125, unseen acc:0.4062, H:0.5417
per-class acc:0.7109, seen acc:1.0000, unseen acc:0.4219, H:0.5934
per-class acc:0.8450, seen acc:0.8333, unseen acc:0.8567, H:0.8448
per-class acc:0.7911, seen acc:0.9000, unseen acc:0.6823, H:0.7762
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     92.43 ± 3.58
Unseen:   45.25 ± 12.04
H-mean:   54.54 ± 12.16
angry -> proud
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7039, seen acc:1.0000, unseen acc:0.4079, H:0.5794
per-class acc:0.6748, seen acc:0.9286, unseen acc:0.4211, H:0.5794
per-class acc:0.9737, seen acc:1.0000, unseen acc:0.9474, H:0.9730
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     98.81 ± 1.19
Unseen:   46.27 ± 12.34
H-mean:   57.75 ± 12.98
angry -> strutting
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7447, seen acc:1.0000, unseen acc:0.4894, H:0.6571
per-class acc:0.6197, seen acc:0.7500, unseen acc:0.4894, H:0.5923
per-class acc:1.0000, seen acc:1.0000, unseen acc:1.0000, H:1.0000
per-class acc:0.6500, seen acc:0.8000, unseen acc:0.5000, H:0.6154
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     84.17 ± 8.21
Unseen:   49.65 ± 12.91
H-mean:   56.08 ± 13.22
childlike -> angry
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7727, seen acc:1.0000, unseen acc:0.5453, H:0.7058
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5833, seen acc:1.0000, unseen acc:0.1667, H:0.2857
Seen:     97.92 ± 2.08
Unseen:   36.87 ± 9.30
H-mean:   49.35 ± 11.72
childlike -> depressed
per-class acc:0.7440, seen acc:0.9231, unseen acc:0.5649, H:0.7009
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5322, seen acc:0.9286, unseen acc:0.1359, H:0.2371
per-class acc:0.7317, seen acc:1.0000, unseen acc:0.4634, H:0.6333
per-class acc:0.8133, seen acc:0.8333, unseen acc:0.7934, H:0.8129
per-class acc:0.4821, seen acc:0.9643, unseen acc:0.0000, H:0.0000
Seen:     94.15 ± 2.55
Unseen:   32.63 ± 13.45
H-mean:   39.74 ± 14.85
childlike -> neutral
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7768, seen acc:1.0000, unseen acc:0.5536, H:0.7127
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.9239, seen acc:1.0000, unseen acc:0.8478, H:0.9176
per-class acc:0.4881, seen acc:0.9545, unseen acc:0.0217, H:0.0425
Seen:     97.16 ± 2.07
Unseen:   40.39 ± 13.50
H-mean:   49.60 ± 15.55
childlike -> old
per-class acc:0.7927, seen acc:1.0000, unseen acc:0.5853, H:0.7384
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5639, seen acc:1.0000, unseen acc:0.1279, H:0.2268
per-class acc:0.5217, seen acc:1.0000, unseen acc:0.0435, H:0.0833
per-class acc:0.4833, seen acc:0.8846, unseen acc:0.0819, H:0.1500
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     95.30 ± 3.05
Unseen:   13.98 ± 9.14
H-mean:   19.98 ± 11.35
childlike -> proud
per-class acc:0.8883, seen acc:0.9583, unseen acc:0.8182, H:0.8827
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.8421, seen acc:1.0000, unseen acc:0.6842, H:0.8125
per-class acc:0.7697, seen acc:1.0000, unseen acc:0.5395, H:0.7009
per-class acc:0.7417, seen acc:0.9583, unseen acc:0.5250, H:0.6784
per-class acc:0.5682, seen acc:1.0000, unseen acc:0.1364, H:0.2400
Seen:     98.61 ± 0.88
Unseen:   45.05 ± 12.97
H-mean:   55.24 ± 14.35
childlike -> strutting
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4178, seen acc:0.7500, unseen acc:0.0856, H:0.1536
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     93.75 ± 4.27
Unseen:   26.43 ± 10.62
H-mean:   35.39 ± 13.74
depressed -> angry
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7206, seen acc:1.0000, unseen acc:0.4412, H:0.6122
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7132, seen acc:0.5000, unseen acc:0.9265, H:0.6495
per-class acc:0.7000, seen acc:0.9000, unseen acc:0.5000, H:0.6429
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     73.33 ± 10.54
Unseen:   47.79 ± 12.01
H-mean:   48.41 ± 10.06
depressed -> childlike
per-class acc:0.4932, seen acc:0.5000, unseen acc:0.4865, H:0.4932
per-class acc:0.6535, seen acc:0.9375, unseen acc:0.3696, H:0.5301
per-class acc:0.4764, seen acc:0.5833, unseen acc:0.3696, H:0.4525
per-class acc:0.6658, seen acc:0.3750, unseen acc:0.9565, H:0.5388
per-class acc:0.6182, seen acc:0.7500, unseen acc:0.4865, H:0.5902
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     69.10 ± 10.13
Unseen:   44.48 ± 12.58
H-mean:   43.41 ± 8.88
depressed -> neutral
per-class acc:0.6364, seen acc:0.7727, unseen acc:0.5000, H:0.6071
per-class acc:0.7222, seen acc:1.0000, unseen acc:0.4444, H:0.6154
per-class acc:0.4815, seen acc:0.5000, unseen acc:0.4630, H:0.4808
per-class acc:0.9190, seen acc:0.8750, unseen acc:0.9630, H:0.9169
per-class acc:0.6389, seen acc:0.7778, unseen acc:0.5000, H:0.6087
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     82.09 ± 7.62
Unseen:   47.84 ± 12.46
H-mean:   53.81 ± 12.28
depressed -> old
per-class acc:0.6674, seen acc:0.9000, unseen acc:0.4348, H:0.5863
per-class acc:0.6953, seen acc:1.0000, unseen acc:0.3906, H:0.5618
per-class acc:0.4609, seen acc:0.5000, unseen acc:0.4219, H:0.4576
per-class acc:0.9205, seen acc:1.0000, unseen acc:0.8410, H:0.9137
per-class acc:0.7174, seen acc:1.0000, unseen acc:0.4348, H:0.6061
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     90.00 ± 8.16
Unseen:   42.05 ± 10.88
H-mean:   52.09 ± 12.15
depressed -> proud
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7039, seen acc:1.0000, unseen acc:0.4079, H:0.5794
per-class acc:0.4803, seen acc:0.5000, unseen acc:0.4605, H:0.4795
per-class acc:0.7303, seen acc:0.5000, unseen acc:0.9605, H:0.6577
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     75.00 ± 11.18
Unseen:   47.15 ± 12.48
H-mean:   48.05 ± 10.12
depressed -> strutting
per-class acc:0.4926, seen acc:0.5000, unseen acc:0.4853, H:0.4925
per-class acc:0.6755, seen acc:1.0000, unseen acc:0.3511, H:0.5197
per-class acc:0.4947, seen acc:0.5000, unseen acc:0.4894, H:0.4946
per-class acc:0.6755, seen acc:0.5000, unseen acc:0.8511, H:0.6299
per-class acc:0.6426, seen acc:0.8000, unseen acc:0.4853, H:0.6041
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     71.67 ± 10.14
Unseen:   44.37 ± 11.21
H-mean:   45.68 ± 9.43
neutral -> angry
per-class acc:0.7188, seen acc:0.9375, unseen acc:0.5000, H:0.6522
per-class acc:0.4884, seen acc:0.7857, unseen acc:0.1912, H:0.3075
per-class acc:0.5678, seen acc:0.9444, unseen acc:0.1912, H:0.3180
per-class acc:0.8956, seen acc:0.8500, unseen acc:0.9412, H:0.8933
per-class acc:0.7250, seen acc:0.9500, unseen acc:0.5000, H:0.6552
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     91.13 ± 3.20
Unseen:   38.73 ± 13.65
H-mean:   47.10 ± 13.13
neutral -> childlike
per-class acc:0.6354, seen acc:0.7708, unseen acc:0.5000, H:0.6066
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4583, seen acc:0.9167, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5109, seen acc:0.5000, unseen acc:0.5217, H:0.5106
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     67.01 ± 7.84
Unseen:   25.36 ± 11.35
H-mean:   26.95 ± 12.15
neutral -> depressed
per-class acc:0.6401, seen acc:0.7802, unseen acc:0.5000, H:0.6094
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.2857, seen acc:0.5714, unseen acc:0.0000, H:0.0000
per-class acc:0.8394, seen acc:0.8636, unseen acc:0.8152, H:0.8387
per-class acc:0.6083, seen acc:0.7167, unseen acc:0.5000, H:0.5890
per-class acc:0.4107, seen acc:0.8214, unseen acc:0.0000, H:0.0000
Seen:     70.89 ± 5.90
Unseen:   30.25 ± 14.32
H-mean:   33.95 ± 15.60
neutral -> old
per-class acc:0.7000, seen acc:0.9000, unseen acc:0.5000, H:0.6429
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7240, seen acc:0.6667, unseen acc:0.7812, H:0.7194
per-class acc:0.7308, seen acc:0.5000, unseen acc:0.9615, H:0.6579
per-class acc:0.3889, seen acc:0.7778, unseen acc:0.0000, H:0.0000
Seen:     72.41 ± 8.44
Unseen:   37.38 ± 17.76
H-mean:   33.67 ± 15.09
neutral -> proud
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.4704, seen acc:0.8750, unseen acc:0.0658, H:0.1224
per-class acc:0.5009, seen acc:0.8571, unseen acc:0.1447, H:0.2477
per-class acc:0.9408, seen acc:1.0000, unseen acc:0.8816, H:0.9371
per-class acc:0.7083, seen acc:0.9167, unseen acc:0.5000, H:0.6471
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     92.06 ± 2.63
Unseen:   34.87 ± 13.82
H-mean:   43.18 ± 14.83
neutral -> strutting
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.2979, seen acc:0.5000, unseen acc:0.0957, H:0.1607
per-class acc:0.2979, seen acc:0.5000, unseen acc:0.0957, H:0.1607
per-class acc:0.9894, seen acc:1.0000, unseen acc:0.9787, H:0.9892
per-class acc:0.6500, seen acc:0.8000, unseen acc:0.5000, H:0.6154
per-class acc:0.4792, seen acc:0.9583, unseen acc:0.0000, H:0.0000
Seen:     79.31 ± 9.74
Unseen:   36.17 ± 15.18
H-mean:   43.21 ± 15.63
old -> angry
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.7059, seen acc:1.0000, unseen acc:0.4118, H:0.5833
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.4845, seen acc:0.5000, unseen acc:0.4689, H:0.4840
per-class acc:0.3750, seen acc:0.7500, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     70.83 ± 10.03
Unseen:   23.01 ± 10.36
H-mean:   26.12 ± 11.76
old -> childlike
per-class acc:0.2593, seen acc:0.5000, unseen acc:0.0185, H:0.0357
per-class acc:0.6848, seen acc:1.0000, unseen acc:0.3696, H:0.5397
per-class acc:0.6326, seen acc:0.7500, unseen acc:0.5153, H:0.6109
per-class acc:0.4348, seen acc:0.5000, unseen acc:0.3696, H:0.4250
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5093, seen acc:1.0000, unseen acc:0.0185, H:0.0364
Seen:     79.17 ± 10.03
Unseen:   21.52 ± 9.33
H-mean:   27.46 ± 11.48
old -> depressed
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.6393, seen acc:0.9091, unseen acc:0.3696, H:0.5255
per-class acc:0.5070, seen acc:0.5000, unseen acc:0.5140, H:0.5069
per-class acc:0.4659, seen acc:0.5000, unseen acc:0.4319, H:0.4634
per-class acc:0.4208, seen acc:0.8417, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     70.20 ± 9.17
Unseen:   21.92 ± 9.98
H-mean:   24.93 ± 11.18
old -> neutral
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.6296, seen acc:1.0000, unseen acc:0.2593, H:0.4118
per-class acc:0.4722, seen acc:0.5000, unseen acc:0.4444, H:0.4706
per-class acc:0.6701, seen acc:0.8125, unseen acc:0.5278, H:0.6399
per-class acc:0.3889, seen acc:0.7778, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     76.50 ± 9.19
Unseen:   20.52 ± 9.84
H-mean:   25.37 ± 11.75
old -> proud
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.7171, seen acc:1.0000, unseen acc:0.4342, H:0.6055
per-class acc:0.4868, seen acc:0.5000, unseen acc:0.4737, H:0.4865
per-class acc:0.6423, seen acc:0.5000, unseen acc:0.7847, H:0.6108
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     75.00 ± 11.18
Unseen:   28.21 ± 13.55
H-mean:   28.38 ± 12.82
old -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.6170, seen acc:1.0000, unseen acc:0.2340, H:0.3793
per-class acc:0.4947, seen acc:0.5000, unseen acc:0.4894, H:0.4946
per-class acc:0.3936, seen acc:0.5000, unseen acc:0.2872, H:0.3649
per-class acc:0.4000, seen acc:0.8000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     71.67 ± 10.14
Unseen:   16.84 ± 8.30
H-mean:   20.65 ± 9.41
proud -> angry
per-class acc:0.4134, seen acc:0.8125, unseen acc:0.0143, H:0.0281
per-class acc:0.5312, seen acc:0.5000, unseen acc:0.5625, H:0.5294
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7500, seen acc:0.5000, unseen acc:1.0000, H:0.6667
per-class acc:0.2643, seen acc:0.5000, unseen acc:0.0286, H:0.0541
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     71.88 ± 10.17
Unseen:   35.09 ± 16.62
H-mean:   32.41 ± 13.45
proud -> childlike
per-class acc:0.3333, seen acc:0.6667, unseen acc:0.0000, H:0.0000
per-class acc:0.5109, seen acc:0.5000, unseen acc:0.5217, H:0.5106
per-class acc:0.7391, seen acc:1.0000, unseen acc:0.4783, H:0.6471
per-class acc:0.7324, seen acc:0.5000, unseen acc:0.9647, H:0.6586
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4792, seen acc:0.9583, unseen acc:0.0000, H:0.0000
Seen:     68.75 ± 9.61
Unseen:   32.75 ± 16.21
H-mean:   30.27 ± 13.70
proud -> depressed
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4545, seen acc:0.4091, unseen acc:0.5000, H:0.4500
per-class acc:0.7391, seen acc:1.0000, unseen acc:0.4783, H:0.6471
per-class acc:0.5610, seen acc:0.5000, unseen acc:0.6220, H:0.5543
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     72.84 ± 11.66
Unseen:   26.67 ± 12.09
H-mean:   27.52 ± 12.57
proud -> neutral
per-class acc:0.4773, seen acc:0.9545, unseen acc:0.0000, H:0.0000
per-class acc:0.5870, seen acc:0.5000, unseen acc:0.6739, H:0.5741
per-class acc:0.7002, seen acc:0.9375, unseen acc:0.4630, H:0.6198
per-class acc:0.7315, seen acc:0.5000, unseen acc:0.9630, H:0.6582
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     73.20 ± 10.41
Unseen:   35.00 ± 16.94
H-mean:   30.87 ± 13.85
proud -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4643, seen acc:0.4286, unseen acc:0.5000, H:0.4615
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4688, seen acc:0.9375, unseen acc:0.0000, H:0.0000
Seen:     72.77 ± 11.34
Unseen:   25.00 ± 11.18
H-mean:   27.14 ± 12.46
proud -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.4853, seen acc:0.2500, unseen acc:0.7206, H:0.3712
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     62.50 ± 12.50
Unseen:   28.68 ± 13.24
H-mean:   25.63 ± 12.08
strutting -> angry
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.6786, seen acc:0.8571, unseen acc:0.5000, H:0.6316
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7000, seen acc:0.4000, unseen acc:1.0000, H:0.5714
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     62.62 ± 9.87
Unseen:   50.00 ± 12.91
H-mean:   45.05 ± 9.27
strutting -> childlike
per-class acc:0.4932, seen acc:0.5000, unseen acc:0.4865, H:0.4932
per-class acc:0.5095, seen acc:0.5625, unseen acc:0.4565, H:0.5040
per-class acc:0.4783, seen acc:0.5000, unseen acc:0.4565, H:0.4773
per-class acc:0.6454, seen acc:0.3125, unseen acc:0.9783, H:0.4737
per-class acc:0.4932, seen acc:0.5000, unseen acc:0.4865, H:0.4932
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     56.25 ± 9.41
Unseen:   47.74 ± 12.65
H-mean:   40.69 ± 8.15
strutting -> depressed
per-class acc:0.2622, seen acc:0.5000, unseen acc:0.0244, H:0.0465
per-class acc:0.5370, seen acc:0.6500, unseen acc:0.4239, H:0.5132
per-class acc:0.4728, seen acc:0.5000, unseen acc:0.4457, H:0.4713
per-class acc:0.6085, seen acc:0.2727, unseen acc:0.9443, H:0.4232
per-class acc:0.2622, seen acc:0.5000, unseen acc:0.0244, H:0.0465
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     56.40 ± 9.36
Unseen:   31.04 ± 15.20
H-mean:   25.01 ± 9.89
strutting -> neutral
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.6243, seen acc:0.7857, unseen acc:0.4630, H:0.5826
per-class acc:0.4907, seen acc:0.5000, unseen acc:0.4815, H:0.4906
per-class acc:0.5907, seen acc:0.2000, unseen acc:0.9815, H:0.3323
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     58.10 ± 11.29
Unseen:   48.77 ± 12.68
H-mean:   40.09 ± 8.68
strutting -> old
per-class acc:0.2826, seen acc:0.5000, unseen acc:0.0652, H:0.1154
per-class acc:0.5547, seen acc:0.6875, unseen acc:0.4219, H:0.5229
per-class acc:0.4609, seen acc:0.5000, unseen acc:0.4219, H:0.4576
per-class acc:0.6644, seen acc:0.5000, unseen acc:0.8288, H:0.6237

## m1: seperate after encoder

In [12]:
def main_m1(args):
    set_seed(args)

    device = torch.device('cuda' if torch.cuda.is_available() else 'cpu')

    datasets, data_loaders = get_datesets_and_loaders(
        args=args,
        DOMAIN_SET=DOMAIN_SET,
        DATA_DIR=DATA_DIR,
        DATASET_DETAILS=DATASET_DETAILS)

    vae = get_trained_VAE_with_domain_classifier(
        data_loaders=data_loaders,
        args=args,
        device=device)
        
    classifier = get_trained_classifier(
        data_loaders=data_loaders,
        vae=vae,
        NUM_LABELS=NUM_LABELS,
        device=device,
        change_policy_epoch=30,
        input_dim=512)

    return test_model(classifier, datasets['test'], data_loaders['test'], device)

In [13]:
result["Our+GRE"] = run_all_senario(main_m1, DOMAIN_SET, input_dim=512, num_trial=6)

angry -> childlike
per-class acc:0.7188, seen acc:0.9375, unseen acc:0.5000, H:0.6522
per-class acc:0.6671, seen acc:0.8125, unseen acc:0.5217, H:0.6354
per-class acc:0.7065, seen acc:1.0000, unseen acc:0.4130, H:0.5846
per-class acc:0.8845, seen acc:0.8125, unseen acc:0.9565, H:0.8786
per-class acc:0.5417, seen acc:0.5833, unseen acc:0.5000, H:0.5385
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     85.76 ± 6.49
Unseen:   48.19 ± 12.44
H-mean:   54.82 ± 11.97
angry -> depressed
per-class acc:0.6932, seen acc:0.9231, unseen acc:0.4634, H:0.6171
per-class acc:0.6315, seen acc:0.8500, unseen acc:0.4130, H:0.5559
per-class acc:0.7011, seen acc:1.0000, unseen acc:0.4022, H:0.5736
per-class acc:0.8755, seen acc:0.8636, unseen acc:0.8873, H:0.8753
per-class acc:0.5885, seen acc:0.5625, unseen acc:0.6145, H:0.5874
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     86.65 ± 6.62
Unseen:   46.34 ± 11.88
H-mean:   53.49 ± 11.74
angry -> neutral
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7222, seen acc:1.0000, unseen acc:0.4444, H:0.6154
per-class acc:0.7222, seen acc:1.0000, unseen acc:0.4444, H:0.6154
per-class acc:0.9722, seen acc:1.0000, unseen acc:0.9444, H:0.9714
per-class acc:0.5882, seen acc:0.6111, unseen acc:0.5652, H:0.5873
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     93.52 ± 6.48
Unseen:   48.31 ± 12.33
H-mean:   57.60 ± 12.90
angry -> old
per-class acc:0.6413, seen acc:1.0000, unseen acc:0.2826, H:0.4407
per-class acc:0.5781, seen acc:0.7500, unseen acc:0.4062, H:0.5270
per-class acc:0.7109, seen acc:1.0000, unseen acc:0.4219, H:0.5934
per-class acc:0.8015, seen acc:0.8333, unseen acc:0.7697, H:0.8003
per-class acc:0.8463, seen acc:0.9000, unseen acc:0.7926, H:0.8429
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     91.39 ± 4.31
Unseen:   44.55 ± 12.28
H-mean:   53.40 ± 12.43
angry -> proud
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6974, seen acc:1.0000, unseen acc:0.3947, H:0.5660
per-class acc:0.7105, seen acc:1.0000, unseen acc:0.4211, H:0.5926
per-class acc:0.9803, seen acc:1.0000, unseen acc:0.9605, H:0.9799
per-class acc:0.7625, seen acc:1.0000, unseen acc:0.5250, H:0.6885
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     100.00 ± 0.00
Unseen:   46.69 ± 12.56
H-mean:   58.23 ± 13.11
angry -> strutting
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7447, seen acc:1.0000, unseen acc:0.4894, H:0.6571
per-class acc:0.6197, seen acc:0.7500, unseen acc:0.4894, H:0.5923
per-class acc:0.9947, seen acc:1.0000, unseen acc:0.9894, H:0.9947
per-class acc:0.6000, seen acc:0.7000, unseen acc:0.5000, H:0.5833
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     90.83 ± 5.83
Unseen:   49.47 ± 12.77
H-mean:   58.23 ± 13.19
childlike -> angry
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7567, seen acc:1.0000, unseen acc:0.5135, H:0.6785
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6875, seen acc:0.8750, unseen acc:0.5000, H:0.6364
per-class acc:0.5312, seen acc:1.0000, unseen acc:0.0625, H:0.1176
Seen:     97.92 ± 2.08
Unseen:   34.60 ± 9.99
H-mean:   46.10 ± 12.82
childlike -> depressed
per-class acc:0.7976, seen acc:0.9231, unseen acc:0.6720, H:0.7778
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5536, seen acc:0.8571, unseen acc:0.2500, H:0.3871
per-class acc:0.7317, seen acc:1.0000, unseen acc:0.4634, H:0.6333
per-class acc:0.7578, seen acc:0.8333, unseen acc:0.6822, H:0.7503
per-class acc:0.5357, seen acc:0.9643, unseen acc:0.1071, H:0.1929
Seen:     92.96 ± 2.93
Unseen:   36.25 ± 11.80
H-mean:   45.69 ± 12.96
childlike -> neutral
per-class acc:0.7533, seen acc:0.8750, unseen acc:0.6316, H:0.7336
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7963, seen acc:1.0000, unseen acc:0.5926, H:0.7442
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.9022, seen acc:1.0000, unseen acc:0.8043, H:0.8916
per-class acc:0.5013, seen acc:0.9545, unseen acc:0.0481, H:0.0915
Seen:     97.16 ± 2.07
Unseen:   42.94 ± 13.45
H-mean:   52.13 ± 15.38
childlike -> old
per-class acc:0.8390, seen acc:1.0000, unseen acc:0.6779, H:0.8081
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5370, seen acc:1.0000, unseen acc:0.0741, H:0.1379
per-class acc:0.5326, seen acc:1.0000, unseen acc:0.0652, H:0.1224
per-class acc:0.4448, seen acc:0.8462, unseen acc:0.0435, H:0.0827
per-class acc:0.4259, seen acc:0.8333, unseen acc:0.0185, H:0.0362
Seen:     94.66 ± 3.38
Unseen:   14.65 ± 10.69
H-mean:   19.79 ± 12.38
childlike -> proud
per-class acc:0.9337, seen acc:0.9583, unseen acc:0.9091, H:0.9331
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7632, seen acc:1.0000, unseen acc:0.5263, H:0.6897
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7292, seen acc:0.9583, unseen acc:0.5000, H:0.6571
per-class acc:0.7045, seen acc:1.0000, unseen acc:0.4091, H:0.5806
Seen:     98.61 ± 0.88
Unseen:   47.41 ± 11.86
H-mean:   58.79 ± 12.73
childlike -> strutting
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.4185, seen acc:0.7500, unseen acc:0.0870, H:0.1558
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6719, seen acc:0.8438, unseen acc:0.5000, H:0.6279
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     93.23 ± 4.45
Unseen:   26.45 ± 10.61
H-mean:   35.28 ± 13.67
depressed -> angry
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7143, seen acc:0.9286, unseen acc:0.5000, H:0.6500
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.8750, seen acc:0.7500, unseen acc:1.0000, H:0.8571
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     69.64 ± 9.39
Unseen:   50.00 ± 12.91
H-mean:   50.12 ± 11.55
depressed -> childlike
per-class acc:0.4932, seen acc:0.5000, unseen acc:0.4865, H:0.4932
per-class acc:0.6033, seen acc:0.7500, unseen acc:0.4565, H:0.5676
per-class acc:0.6449, seen acc:0.8333, unseen acc:0.4565, H:0.5899
per-class acc:0.7481, seen acc:0.5179, unseen acc:0.9783, H:0.6772
per-class acc:0.4932, seen acc:0.5000, unseen acc:0.4865, H:0.4932
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     68.35 ± 8.60
Unseen:   47.74 ± 12.65
H-mean:   47.02 ± 9.81
depressed -> neutral
per-class acc:0.6591, seen acc:0.8182, unseen acc:0.5000, H:0.6207
per-class acc:0.6693, seen acc:0.8571, unseen acc:0.4815, H:0.6166
per-class acc:0.4907, seen acc:0.5000, unseen acc:0.4815, H:0.4906
per-class acc:0.8782, seen acc:0.7750, unseen acc:0.9815, H:0.8661
per-class acc:0.5278, seen acc:0.5556, unseen acc:0.5000, H:0.5263
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     75.10 ± 7.74
Unseen:   49.07 ± 12.68
H-mean:   52.00 ± 11.70
depressed -> old
per-class acc:0.6674, seen acc:0.9000, unseen acc:0.4348, H:0.5863
per-class acc:0.5312, seen acc:0.5625, unseen acc:0.5000, H:0.5294
per-class acc:0.7344, seen acc:1.0000, unseen acc:0.4688, H:0.6383
per-class acc:0.9227, seen acc:0.8889, unseen acc:0.9565, H:0.9215
per-class acc:0.5674, seen acc:0.7000, unseen acc:0.4348, H:0.5364
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     84.19 ± 7.16
Unseen:   46.58 ± 12.39
H-mean:   53.53 ± 12.23
depressed -> proud
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.6678, seen acc:0.8750, unseen acc:0.4605, H:0.6034
per-class acc:0.4803, seen acc:0.5000, unseen acc:0.4605, H:0.4795
per-class acc:0.7681, seen acc:0.5625, unseen acc:0.9737, H:0.7131
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     73.96 ± 10.00
Unseen:   48.25 ± 12.59
H-mean:   49.38 ± 10.55
depressed -> strutting
per-class acc:0.4926, seen acc:0.5000, unseen acc:0.4853, H:0.4925
per-class acc:0.7030, seen acc:0.9167, unseen acc:0.4894, H:0.6381
per-class acc:0.4947, seen acc:0.5000, unseen acc:0.4894, H:0.4946
per-class acc:0.7500, seen acc:0.5000, unseen acc:1.0000, H:0.6667
per-class acc:0.4926, seen acc:0.5000, unseen acc:0.4853, H:0.4925
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     65.28 ± 9.72
Unseen:   49.16 ± 12.91
H-mean:   46.41 ± 9.82
neutral -> angry
per-class acc:0.7188, seen acc:0.9375, unseen acc:0.5000, H:0.6522
per-class acc:0.5599, seen acc:0.9286, unseen acc:0.1912, H:0.3171
per-class acc:0.5678, seen acc:0.9444, unseen acc:0.1912, H:0.3180
per-class acc:0.9029, seen acc:0.8500, unseen acc:0.9559, H:0.8998
per-class acc:0.7354, seen acc:0.9500, unseen acc:0.5208, H:0.6728
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     93.51 ± 1.98
Unseen:   39.32 ± 13.91
H-mean:   47.66 ± 13.24
neutral -> childlike
per-class acc:0.6354, seen acc:0.7708, unseen acc:0.5000, H:0.6066
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5312, seen acc:0.5625, unseen acc:0.5000, H:0.5294
per-class acc:0.5217, seen acc:0.5000, unseen acc:0.5435, H:0.5208
per-class acc:0.4167, seen acc:0.8333, unseen acc:0.0000, H:0.0000
Seen:     69.44 ± 8.40
Unseen:   25.72 ± 11.52
H-mean:   27.61 ± 12.41
neutral -> depressed
per-class acc:0.6758, seen acc:0.8516, unseen acc:0.5000, H:0.6301
per-class acc:0.3250, seen acc:0.6500, unseen acc:0.0000, H:0.0000
per-class acc:0.3571, seen acc:0.7143, unseen acc:0.0000, H:0.0000
per-class acc:0.8567, seen acc:0.9091, unseen acc:0.8043, H:0.8535
per-class acc:0.6396, seen acc:0.7792, unseen acc:0.5000, H:0.6091
per-class acc:0.4286, seen acc:0.8571, unseen acc:0.0000, H:0.0000
Seen:     79.36 ± 3.99
Unseen:   30.07 ± 14.19
H-mean:   34.88 ± 15.99
neutral -> old
per-class acc:0.7000, seen acc:0.9000, unseen acc:0.5000, H:0.6429
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.7561, seen acc:0.7778, unseen acc:0.7344, H:0.7555
per-class acc:0.7808, seen acc:0.6000, unseen acc:0.9615, H:0.7389
per-class acc:0.3889, seen acc:0.7778, unseen acc:0.0000, H:0.0000
Seen:     75.93 ± 7.55
Unseen:   36.60 ± 17.42
H-mean:   35.62 ± 16.01
neutral -> proud
per-class acc:0.7083, seen acc:0.9167, unseen acc:0.5000, H:0.6471
per-class acc:0.4638, seen acc:0.8750, unseen acc:0.0526, H:0.0993
per-class acc:0.4878, seen acc:0.8571, unseen acc:0.1184, H:0.2081
per-class acc:0.9474, seen acc:1.0000, unseen acc:0.8947, H:0.9444
per-class acc:0.7292, seen acc:0.9583, unseen acc:0.5000, H:0.6571
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     93.45 ± 2.52
Unseen:   34.43 ± 14.21
H-mean:   42.60 ± 15.35
neutral -> strutting
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.3183, seen acc:0.5833, unseen acc:0.0532, H:0.0975
per-class acc:0.2819, seen acc:0.5000, unseen acc:0.0638, H:0.1132
per-class acc:0.9894, seen acc:1.0000, unseen acc:0.9787, H:0.9892
per-class acc:0.6500, seen acc:0.8000, unseen acc:0.5000, H:0.6154
per-class acc:0.4792, seen acc:0.9583, unseen acc:0.0000, H:0.0000
Seen:     80.69 ± 8.98
Unseen:   34.93 ± 15.63
H-mean:   41.37 ± 16.30
old -> angry
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.7059, seen acc:1.0000, unseen acc:0.4118, H:0.5833
per-class acc:0.6111, seen acc:0.7222, unseen acc:0.5000, H:0.5909
per-class acc:0.4700, seen acc:0.5000, unseen acc:0.4399, H:0.4680
per-class acc:0.3250, seen acc:0.6500, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     72.87 ± 9.27
Unseen:   22.53 ± 10.14
H-mean:   27.37 ± 12.37
old -> childlike
per-class acc:0.2593, seen acc:0.5000, unseen acc:0.0185, H:0.0357
per-class acc:0.6848, seen acc:1.0000, unseen acc:0.3696, H:0.5397
per-class acc:0.6743, seen acc:0.8333, unseen acc:0.5153, H:0.6368
per-class acc:0.4348, seen acc:0.5000, unseen acc:0.3696, H:0.4250
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5093, seen acc:1.0000, unseen acc:0.0185, H:0.0364
Seen:     80.56 ± 10.02
Unseen:   21.52 ± 9.33
H-mean:   27.89 ± 11.74
old -> depressed
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.6393, seen acc:0.9091, unseen acc:0.3696, H:0.5255
per-class acc:0.5695, seen acc:0.6429, unseen acc:0.4961, H:0.5600
per-class acc:0.4354, seen acc:0.5000, unseen acc:0.3709, H:0.4259
per-class acc:0.4208, seen acc:0.8417, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     72.59 ± 8.40
Unseen:   20.61 ± 9.41
H-mean:   25.19 ± 11.41
old -> neutral
per-class acc:0.3182, seen acc:0.6364, unseen acc:0.0000, H:0.0000
per-class acc:0.6204, seen acc:1.0000, unseen acc:0.2407, H:0.3881
per-class acc:0.5752, seen acc:0.6875, unseen acc:0.4630, H:0.5533
per-class acc:0.6568, seen acc:0.8125, unseen acc:0.5012, H:0.6199
per-class acc:0.3889, seen acc:0.7778, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     81.90 ± 6.27
Unseen:   20.08 ± 9.69
H-mean:   26.02 ± 12.04
old -> proud
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.7039, seen acc:1.0000, unseen acc:0.4079, H:0.5794
per-class acc:0.4868, seen acc:0.5000, unseen acc:0.4737, H:0.4865
per-class acc:0.6423, seen acc:0.5000, unseen acc:0.7847, H:0.6108
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     75.00 ± 11.18
Unseen:   27.77 ± 13.46
H-mean:   27.95 ± 12.61
old -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.6117, seen acc:1.0000, unseen acc:0.2234, H:0.3652
per-class acc:0.4947, seen acc:0.5000, unseen acc:0.4894, H:0.4946
per-class acc:0.3830, seen acc:0.5000, unseen acc:0.2660, H:0.3472
per-class acc:0.4000, seen acc:0.8000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     71.67 ± 10.14
Unseen:   16.31 ± 8.17
H-mean:   20.12 ± 9.23
proud -> angry
per-class acc:0.4134, seen acc:0.8125, unseen acc:0.0143, H:0.0281
per-class acc:0.5104, seen acc:0.5000, unseen acc:0.5208, H:0.5102
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.7500, seen acc:0.5000, unseen acc:1.0000, H:0.6667
per-class acc:0.2643, seen acc:0.5000, unseen acc:0.0286, H:0.0541
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     71.88 ± 10.17
Unseen:   34.39 ± 16.46
H-mean:   32.09 ± 13.35
proud -> childlike
per-class acc:0.2917, seen acc:0.5833, unseen acc:0.0000, H:0.0000
per-class acc:0.5109, seen acc:0.5000, unseen acc:0.5217, H:0.5106
per-class acc:0.7391, seen acc:1.0000, unseen acc:0.4783, H:0.6471
per-class acc:0.7324, seen acc:0.5000, unseen acc:0.9647, H:0.6586
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4792, seen acc:0.9583, unseen acc:0.0000, H:0.0000
Seen:     67.36 ± 9.77
Unseen:   32.75 ± 16.21
H-mean:   30.27 ± 13.70
proud -> depressed
per-class acc:0.4643, seen acc:0.9286, unseen acc:0.0000, H:0.0000
per-class acc:0.4545, seen acc:0.4091, unseen acc:0.5000, H:0.4500
per-class acc:0.7283, seen acc:1.0000, unseen acc:0.4565, H:0.6269
per-class acc:0.5806, seen acc:0.5000, unseen acc:0.6612, H:0.5694
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     71.65 ± 11.16
Unseen:   26.96 ± 12.37
H-mean:   27.44 ± 12.49
proud -> neutral
per-class acc:0.4545, seen acc:0.9091, unseen acc:0.0000, H:0.0000
per-class acc:0.5109, seen acc:0.5000, unseen acc:0.5217, H:0.5106
per-class acc:0.7002, seen acc:0.9375, unseen acc:0.4630, H:0.6198
per-class acc:0.7315, seen acc:0.5000, unseen acc:0.9630, H:0.6582
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     72.44 ± 10.11
Unseen:   32.46 ± 16.14
H-mean:   29.81 ± 13.48
proud -> old
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.5109, seen acc:0.5000, unseen acc:0.5217, H:0.5106
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.4375, seen acc:0.8750, unseen acc:0.0000, H:0.0000
Seen:     72.92 ± 10.42
Unseen:   25.36 ± 11.35
H-mean:   27.96 ± 12.73
proud -> strutting
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7500, seen acc:1.0000, unseen acc:0.5000, H:0.6667
per-class acc:0.6066, seen acc:0.3750, unseen acc:0.8382, H:0.5182
per-class acc:0.2500, seen acc:0.5000, unseen acc:0.0000, H:0.0000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     64.58 ± 11.37
Unseen:   30.64 ± 14.60
H-mean:   28.08 ± 12.78
strutting -> angry
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.6429, seen acc:0.7857, unseen acc:0.5000, H:0.6111
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.7000, seen acc:0.4000, unseen acc:1.0000, H:0.5714
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     61.43 ± 9.37
Unseen:   50.00 ± 12.91
H-mean:   44.71 ± 9.14
strutting -> childlike
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5095, seen acc:0.5625, unseen acc:0.4565, H:0.5040
per-class acc:0.4783, seen acc:0.5000, unseen acc:0.4565, H:0.4773
per-class acc:0.6141, seen acc:0.2500, unseen acc:0.9783, H:0.3982
per-class acc:0.4932, seen acc:0.5000, unseen acc:0.4865, H:0.4932
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     55.21 ± 10.00
Unseen:   47.96 ± 12.65
H-mean:   39.54 ± 8.07
strutting -> depressed
per-class acc:0.2622, seen acc:0.5000, unseen acc:0.0244, H:0.0465
per-class acc:0.5370, seen acc:0.6500, unseen acc:0.4239, H:0.5132
per-class acc:0.4620, seen acc:0.5000, unseen acc:0.4239, H:0.4588
per-class acc:0.6085, seen acc:0.2727, unseen acc:0.9443, H:0.4232
per-class acc:0.2622, seen acc:0.5000, unseen acc:0.0244, H:0.0465
per-class acc:0.4808, seen acc:0.9615, unseen acc:0.0000, H:0.0000
Seen:     56.40 ± 9.36
Unseen:   30.68 ± 15.14
H-mean:   24.80 ± 9.80
strutting -> neutral
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5437, seen acc:0.6429, unseen acc:0.4444, H:0.5255
per-class acc:0.4815, seen acc:0.5000, unseen acc:0.4630, H:0.4808
per-class acc:0.5907, seen acc:0.2000, unseen acc:0.9815, H:0.3323
per-class acc:0.5000, seen acc:0.5000, unseen acc:0.5000, H:0.5000
per-class acc:0.5000, seen acc:1.0000, unseen acc:0.0000, H:0.0000
Seen:     55.71 ± 10.66
Unseen:   48.15 ± 12.70
H-mean:   38.98 ± 8.29
strutting -> old
per-class acc:0.2826, seen acc:0.5000, unseen acc:0.0652, H:0.1154
per-class acc:0.5234, seen acc:0.6250, unseen acc:0.4219, H:0.5037
per-class acc:0.4609, seen acc:0.5000, unseen acc:0.4219, H:0.4576
per-class acc:0.6753, seen acc:0.5000, unseen acc:0.8505, H:0.6298


## Merge results

In [14]:
import pandas as pd
import re

rows = [(k, m, result[m][k]) for m in result for k in result[m]]
df = pd.DataFrame(rows, columns=['domain', 'method', 'values'])

def extract_metrics(text):
    matches = dict(re.findall(r'(\w+):\s+([\d.]+\s*±\s*[\d.]+)', text))
    return pd.Series(matches)

df[['seen', 'unseen', 'H-mean']] = df['values'].apply(extract_metrics)
df = df[['domain', 'method', 'seen', 'unseen', 'H-mean']]

df['method'] = pd.Categorical(df['method'], categories=['Base', 'GZSDA', 'Our', 'Our+GRE'], ordered=True)
df = df.sort_values(['domain', 'method']).reset_index(drop=True)

df

                 domain   method           seen         unseen         H-mean
0    angry -> childlike     Base   93.40 ± 2.82  30.35 ± 11.40  38.87 ± 12.93
1    angry -> childlike    GZSDA   90.62 ± 4.19  26.72 ± 11.77  32.82 ± 14.12
2    angry -> childlike      Our   86.81 ± 5.12  46.74 ± 12.14  54.27 ± 11.76
3    angry -> childlike  Our+GRE   85.76 ± 6.49  48.19 ± 12.44  54.82 ± 11.97
4    angry -> depressed     Base   94.08 ± 3.07   15.81 ± 4.59   25.60 ± 6.87
..                  ...      ...            ...            ...            ...
163    strutting -> old  Our+GRE   60.42 ± 8.18  30.41 ± 13.33  30.37 ± 10.54
164  strutting -> proud     Base  75.00 ± 11.18  37.50 ± 13.31   39.63 ± 9.24
165  strutting -> proud    GZSDA  66.67 ± 10.54  28.95 ± 15.51  27.52 ± 12.62
166  strutting -> proud      Our   64.58 ± 9.36  49.56 ± 12.92   46.36 ± 9.71
167  strutting -> proud  Our+GRE   64.58 ± 9.36  49.12 ± 12.92   46.13 ± 9.70

[168 rows x 5 columns]

In [15]:
df.to_csv("./result_actionStyle.csv")

In [16]:
df.groupby("domain")

In [17]:
df["H-mean_value"] = (
    df["unseen"]
    # df["H-mean"]
    .str.split("±")
    .str[0]
    .astype(float)
)
df

,domain,method,seen,unseen,H-mean,H-mean_value
0,angry -> childlike,Base,93.40 ± 2.82,30.35 ± 11.40,38.87 ± 12.93,30.35
1,angry -> childlike,GZSDA,90.62 ± 4.19,26.72 ± 11.77,32.82 ± 14.12,26.72
2,angry -> childlike,Our,86.81 ± 5.12,46.74 ± 12.14,54.27 ± 11.76,46.74
3,angry -> childlike,Our+GRE,85.76 ± 6.49,48.19 ± 12.44,54.82 ± 11.97,48.19
4,angry -> depressed,Base,94.08 ± 3.07,15.81 ± 4.59,25.60 ± 6.87,15.81
...,...,...,...,...,...,...
163,strutting -> old,Our+GRE,60.42 ± 8.18,30.41 ± 13.33,30.37 ± 10.54,30.41
164,strutting -> proud,Base,75.00 ± 11.18,37.50 ± 13.31,39.63 ± 9.24,37.50
165,strutting -> proud,GZSDA,66.67 ± 10.54,28.95 ± 15.51,27.52 ± 12.62,28.95
166,strutting -> proud,Our,64.58 ± 9.36,49.56 ± 12.92,46.36 ± 9.71,49.56
167,strutting -> proud,Our+GRE,64.58 ± 9.36,49.12 ± 12.92,46.13 ± 9.70,49.12

In [18]:
best = df.loc[df.groupby("domain")["H-mean_value"].idxmax()]
best = best[["domain", "method", "H-mean"]].reset_index(drop=True)

best

                    domain   method         H-mean
0       angry -> childlike  Our+GRE  54.82 ± 11.97
1       angry -> depressed  Our+GRE  53.49 ± 11.74
2         angry -> neutral  Our+GRE  57.60 ± 12.90
3             angry -> old      Our  54.54 ± 12.16
4           angry -> proud  Our+GRE  58.23 ± 13.11
5       angry -> strutting      Our  56.08 ± 13.22
6       childlike -> angry      Our  49.35 ± 11.72
7   childlike -> depressed  Our+GRE  45.69 ± 12.96
8     childlike -> neutral  Our+GRE  52.13 ± 15.38
9         childlike -> old  Our+GRE  19.79 ± 12.38
10      childlike -> proud  Our+GRE  58.79 ± 12.73
11  childlike -> strutting  Our+GRE  35.28 ± 13.67
12      depressed -> angry  Our+GRE  50.12 ± 11.55
13  depressed -> childlike  Our+GRE   47.02 ± 9.81
14    depressed -> neutral  Our+GRE  52.00 ± 11.70
15        depressed -> old  Our+GRE  53.53 ± 12.23
16      depressed -> proud  Our+GRE  49.38 ± 10.55
17  depressed -> strutting  Our+GRE   46.41 ± 9.82
18        neutral -> angry  Our+GRE  47.66 ± 13.24
19    neutral -> childlike     Base  32.41 ± 14.50
20    neutral -> depressed      Our  33.95 ± 15.60
21          neutral -> old      Our  33.67 ± 15.09
22        neutral -> proud      Our  43.18 ± 14.83
23    neutral -> strutting      Our  43.21 ± 15.63
24            old -> angry      Our  26.12 ± 11.76
25        old -> childlike      Our  27.46 ± 11.48
26        old -> depressed      Our  24.93 ± 11.18
27          old -> neutral      Our  25.37 ± 11.75
28            old -> proud      Our  28.38 ± 12.82
29        old -> strutting      Our   20.65 ± 9.41
30          proud -> angry     Base  37.02 ± 16.29
31      proud -> childlike      Our  30.27 ± 13.70
32      proud -> depressed  Our+GRE  27.44 ± 12.49
33        proud -> neutral      Our  30.87 ± 13.85
34            proud -> old  Our+GRE  27.96 ± 12.73
35      proud -> strutting  Our+GRE  28.08 ± 12.78
36      strutting -> angry      Our   45.05 ± 9.27
37  strutting -> childlike  Our+GRE   39.54 ± 8.07
38  strutting -> depressed      Our   25.01 ± 9.89
39    strutting -> neutral      Our   40.09 ± 8.68
40        strutting -> old  Our+GRE  30.37 ± 10.54
41      strutting -> proud      Our   46.36 ± 9.71

In [19]:
from collections import Counter
Counter(best.method)

Counter({'Our+GRE': 21, 'Our': 19, 'Base': 2})